apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        # Main Container: Wordpress
        - image: docker.io/wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1:3306
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: DB_NAME
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: DB_PASSWORD
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
        # Sidecar Container: CloudSQL Proxy
        - image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
          name: clousql-proxy
          command: ["/cloud_sql_proxy"]
          args:
            - -instances=$(INSTANCE_CONNECTION_NAME)=tcp:0.0.0.0:3306
            - -credential_file=/etc/sa-key/gks-sa-key.json
          env:
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-connection
                  key: DB_CONNECTION
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: sa-key
              readOnly: true
              mountPath: /etc/sa-key
      volumes:
        - name: sa-key
          secret:
            secretName: cloudsql-sa-key
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim
