apiVersion: v1
kind: Service
metadata:
  name: clousql-proxy
  labels:
    app: clousql-proxy
spec:
  selector:
    app: clousql-proxy
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
