apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress-static-ip
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  backend:
    serviceName: hello
    servicePort: 8080
